# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='folder',
            name='newsNumber',
        ),
        migrations.AddField(
            model_name='folder_news',
            name='folderNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.Folder'),
        ),
        migrations.AddField(
            model_name='folder_news',
            name='newsNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.News'),
        ),
    ]
