# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_auto_20171122_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='id',
        ),
        migrations.AlterField(
            model_name='folder',
            name='folderNumber',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
