# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_auto_20171125_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsFile',
            field=models.TextField(),
        ),
    ]
